name       : haskell-http-client
version    : 0.7.1
release    : 3
source     :
    - https://hackage.haskell.org/package/http-client-0.7.1/http-client-0.7.1.tar.gz : e09abcab72b0b85887ff7c9df25be55a3c1bc2a63e026ff173dd2eccfb954d62
license    : MIT
component  : programming.haskell
summary    : An HTTP client engine, intended as a base layer for more user-friendly packages.
description: |
    An HTTP client engine, intended as a base layer for more user-friendly packages.
builddeps  :
    - haskell-cabal-install
    - haskell-cookie-devel
    - haskell-data-default-devel
    - haskell-exceptions-devel
    - haskell-http-types-devel
    - haskell-memory-devel
    - haskell-mime-types-devel
    - haskell-network-uri-devel
    - haskell-streaming-commons-devel
rundeps    :
    - devel:
        - haskell-cookie-devel
        - haskell-data-default-devel
        - haskell-exceptions-devel
        - haskell-http-types-devel
        - haskell-memory-devel
        - haskell-mime-types-devel
        - haskell-network-uri-devel
        - haskell-streaming-commons-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
