name       : haskell-http-client
version    : 0.5.6.1
release    : 1
source     :
    - http://hackage.haskell.org/package/http-client-0.5.6.1/http-client-0.5.6.1.tar.gz : 2c304337b88ea48cf4b1c4e4ac12ec48c5f3a241f3ab44a57965c1d9d06a2bed
license    : MIT
component  : programming.haskell
summary    : An HTTP client engine, intended as a base layer for more user-friendly packages.
description: |
    An HTTP client engine, intended as a base layer for more user-friendly packages.
builddeps  :
    - haskell-cabal-install
    - haskell-cookie
    - haskell-exceptions
    - haskell-http-types
    - haskell-mime-types
    - haskell-streaming-commons
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
