name       : haskell-http-client
version    : 0.5.12.1
release    : 2
source     :
    - https://hackage.haskell.org/package/http-client-0.5.12.1/http-client-0.5.12.1.tar.gz : 4b5116324d217f0498d258d37135a52f3e69103d3a951b0999618b263c9bd63e
license    : MIT
component  : programming.haskell
summary    : An HTTP client engine, intended as a base layer for more user-friendly packages.
description: |
    An HTTP client engine, intended as a base layer for more user-friendly packages.
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-cookie
    - haskell-exceptions
    - haskell-http-types
    - haskell-memory
    - haskell-mime-types
    - haskell-network
    - haskell-network-uri
    - haskell-streaming-commons
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
